### ISSUE TITLE
Nueva propuesta de wallpaper, no se necesita explicación

### ISSUE THREAD

**Issue by lVoidi** [cyb3r14/dotfiles#1]
![image](https://github.com/user-attachments/assets/77ca2c2e-ac12-4dde-8c31-18c2ad637017)

**Comment by h1d30us** [comment]
ALLAH THE BIGGEST 
![](https://4get.ca/proxy?i=https%3A%2F%2Fcdn.sharechat.com%2F5b4c2c1_1628800154625_sc.gif)
